#!/usr/bin/bash


touch oscarFile
date >> oscarFile
cat /proc/meminfo >> oscarFile
curtime=$(date +%H:%M)
 if [["$curtime" -eq "00:00"]]
then
mail -s 'oscarFile' nnadiukwuoscar@gmail.com < oscarFile
fi
